### ISSUE TITLE
Window Drag Issue

### ISSUE THREAD

**Issue by Novack** [acoppes/unity-history-window#20] opened 2019-08-22 19:49 UTC
In Unity, when you drag windows around, the pointer slightly moves over the title bar with some sort of inertia displacement. 

When you are dragging the History Window, it can happen that the pointer touches a history element and this breaks things up *badly*: window dragging stops, and you are inadvertedly dragging a file or asset around.

Will review this and send a PR as soon as time allows.

**Comment by acoppes** [comment] 2021-05-31 01:28
Can't reproduce the issue, I am using Windows and 2019.4.14f1, could it be related with a specific Unity version or something like that? do you have a video or any idea on how to reproduce the issue? Will close it for now until further info.

**Closed by acoppes** 2021-05-31 01:28 UTC
